## Python 

In [15]:
# you write a python code on the browser, it execute on the server, then the browser prints execution results

In [16]:
my_string = 'Hello'

print(my_string)

Hello


In [7]:
my_list = []


my_list.append(5)
my_list.append(2)
my_list.append(8)

print(my_list, len(my_list))

[5, 2, 8] 3


In [9]:
for item in my_list:
    print('item =', item)

item = 5
item = 2
item = 8


In [13]:
my_test = False
print(not my_test)

True


In [17]:
if (not my_test):
    print('simple if')

simple if


In [19]:
def my_add_function(a, b):
    print(a + b)

my_add_function(5, 8)

13


In [21]:
my_tuple = (1, 2, 3)

print(my_tuple)

(1, 2, 3)


In [25]:
def my_returning_multi_vars_function(a, b):
    return a + b, a * b, a / 2

add, mult, div = my_returning_multi_vars_function(10, 2)

print(add, mult, div)

12 20 5.0


In [29]:
# simple class 

class A():
    def __init__(self, value):
        self.my_attribute = value
        
    def print_attribute_square(self):
        print(self.my_attribute ** 2)
        
# create instance

a = A(5)

a.print_attribute_square()

25


In [43]:
# inheritance

class B(A):
    def __init__(self, value):
        super().__init__(value)
        
    def print_attribute(self):
        print(self.my_attribute)
        
b = B(16)

b.print_attribute()
b.print_attribute_square()

16
256


## Numpy

NumPy is the fundamental package for scientific computing with Python.

NumPy is built around ndarrays objects, which are high-performance multi-dimensional array data structures. 

**Used for matrix manipulation and linear Algebra**

In [40]:
# importing modules

import numpy as np

In [65]:
from numpy import sqrt

sqrt(25)

5.0

### N-dimensional Arrays

In [54]:
my_list = [[1, 2, 3], [4, 5, 6]]
matrix = np.array(my_list)
matrix

array([[1, 2, 3],
       [4, 5, 6]])

<img src="https://github.com/hzitoun/deep-learning-book/raw/839e076c5098084512c947a38878a9a545d9a87d/code/appendix_h_numpy-intro/images/numpy-intro/array_1.png">

In [56]:
matrix.shape

(2, 3)

In [64]:
matrix.size

6

### Indexing

In [67]:
print(matrix[0, 0])
print(matrix[1, 2])

1
6


In [70]:
print(matrix[0, :])

[1 2 3]


In [72]:
print(matrix[:, 1])

[2 5]


### Math and Universal Functions

In [77]:
print(matrix + 10)
print(matrix ** 2)

[[11 12 13]
 [14 15 16]]
[[ 1  4  9]
 [16 25 36]]


In [80]:
print(matrix.sum(axis=0))
print(matrix.sum(axis=1))

[5 7 9]
[ 6 15]


other functions : 
- mean (computes arithmetic average)
- std (computes the standard deviation)
- var (computes variance)
- np.sort (sorts an array)
- np.argsort (returns indices that would sort an array)
- np.min (returns the minimum value of an array)
- np.max (returns the maximum value of an array)
- np.argmin (returns the index of the minimum value)
- np.argmax (returns the index of the maximum value)

In [82]:
matrix2 = np.array([[10, 20, 30], [40, 50, 60]])

matrix + matrix2

array([[11, 22, 33],
       [44, 55, 66]])

In [84]:
matrix * matrix2

array([[ 10,  40,  90],
       [160, 250, 360]])

### Random Number Generators

In machine learning and deep learning, we often have to generate arrays of random numbers -- for example, the initial values of our model parameters before optimization.

In [103]:
# comment and uncomment the first line
np.random.seed(123)
np.random.rand(3)

array([0.69646919, 0.28613933, 0.22685145])

### Linear Algebra


Most of the operations in machine learning and deep learning are based on concepts from linear algebra.

In [105]:
matrix.reshape(-1, 6)

array([[1, 2, 3, 4, 5, 6]])

**matrix multiplication**

To perform matrix multiplication between matrices, we learned that number of columns of the left matrix must match the number of rows of the matrix to the right. In NumPy, we can perform matrix multiplication via the dot function

In [109]:
column_vector = np.array([[1, 2, 3]]).reshape(-1, 1)
matrix.dot(column_vector)

array([[14],
       [32]])

<img src="https://github.com/hzitoun/deep-learning-book/raw/839e076c5098084512c947a38878a9a545d9a87d/code/appendix_h_numpy-intro/images/numpy-intro/matmul.png">

**transpose matrix** 



In [111]:
matrix.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [113]:
np.dot(matrix, matrix.T)

array([[14, 32],
       [32, 77]])

<img src="https://github.com/hzitoun/deep-learning-book/raw/839e076c5098084512c947a38878a9a545d9a87d/code/appendix_h_numpy-intro/images/numpy-intro/matmatmul.png" />